# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'



steps:
- task: HugoTask@1
  inputs:
    source: 
    destination: '$(System.DefaultWorkingDirectory)/public'

- task: S3Upload@1
  inputs:
    regionName: 'us-west-2'
    bucketName: 'brianpsheridan'
    sourceFolder: '$(System.DefaultWorkingDirectory)/public'
    globExpressions: '**'
    filesAcl: 'public-read'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/public'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'website'
    publishLocation: 'Container'




