
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: HugoTask@1
  inputs:
    source: 
    destination: '$(System.DefaultWorkingDirectory)/public'

- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-west-2'
    bucketName: 'brianpsheridan.com'
    sourceFolder: '$(System.DefaultWorkingDirectory)/public'
    globExpressions: '**'
    filesAcl: 'public-read'



