# Site settings
baseurl = "http://brianpsheridan.com"
languageCode = "en-us"
title = "Brian Sheridan"
theme = "spectre-pixel"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  name = "Brian Sheridan"
  altName = "Brian"
  description = "This is a wesbite of my random thoughts and exploration in technology"
  bio = "Leader & Technologist"
  enableRSS = true

  # Author information in posts
  aboutAuthor = "I'm Brian."

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
	email    = "brian.sheridan@gmail.com"
	github   = "https://www.github.com/two4suited"
	linkedin = "https://www.linkedin.com/in/brian-sheridan"
	twitter  = "https://www.twitter.com/brianpsheridan"

[taxonomies]
  tag = "tags"
